/*
 * This file was generated by the Gradle("init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the("Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// from gradle.properties
val jupiterVersion: String by project
val lombokVersion: String by project

dependencies {
    compileOnly("org.projectlombok:lombok:${lombokVersion}")
    annotationProcessor("org.projectlombok:lombok:${lombokVersion}")

    testCompileOnly("org.projectlombok:lombok:${lombokVersion}")
    testAnnotationProcessor("org.projectlombok:lombok:${lombokVersion}")

    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:${jupiterVersion}")
    testImplementation("org.junit.jupiter:junit-jupiter-params:${jupiterVersion}")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:33.3.1-jre")
    implementation("org.jgrapht:jgrapht-core:1.5.2")
    implementation("org.slf4j:slf4j-api:1.7.26")
    implementation("org.javatuples:javatuples:1.2")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
